name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 17 * * *'  # Runs daily at 11 PM IST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install sitemap generator
        run: npm install -g sitemap-generator-cli

      - name: Generate the sitemap
        run: sitemap-generator-cli https://meharphysiotherapyclinic.github.io/website/ -o sitemap.xml --verbose

      - name: Commit and push the sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate sitemap.xml"
          file_pattern: sitemap.xml
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"
          
