name: Update Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"   # Every Sunday at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sitemap dependency
        run: npm install sitemap@3.2.2

      - name: Generate sitemap
        run: node generate-sitemap.js

      - name: Commit sitemap if changed
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add website/sitemap.xml
          git diff --quiet && echo "No changes to commit" || (git commit -m "Auto-update sitemap" && git push origin HEAD:main)

      - name: Ping Google & Bing
        run: |
          curl "https://www.google.com/ping?sitemap=https://meharphysiotherapyclinic.github.io/website/sitemap.xml"
          curl "https://www.bing.com/ping?sitemap=https://meharphysiotherapyclinic.github.io/website/sitemap.xml"
